// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "github.com/CloverOS/goctl-swag/testdata/go-zero/user/internal/handler/login"
	user "github.com/CloverOS/goctl-swag/testdata/go-zero/user/internal/handler/user"
	"github.com/CloverOS/goctl-swag/testdata/go-zero/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/users/login",
				Handler: login.JsonLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/form/login",
				Handler: login.FormLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get/captcha/:key",
				Handler: login.GetcaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/login"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/list/:page/:count",
				Handler: user.UserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/edit/myheadimg",
				Handler: user.EditMyHeadImgsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: user.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/file/download",
				Handler: user.DownloadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/fileserver"),
	)
}
