// Code generated by goctl. DO NOT EDIT.
package types

type MyResponse struct {
	Code int    `json:"code"` //错误码
	Msg  string `json:"msg"`  //错误消息
}

type PageRequest struct {
	Page     int    `path:"page"`     //页数:1开始
	Count    int    `path:"count"`    //每页数量
	NickName string `json:"nickName"` //昵称
}

type JsonRequest struct {
	RequestId string `header:"requestId"`       //请求id
	Account   string `json:"account"`           //账号
	Password  string `json:"password"`          //密码
	SecCode   string `json:"sec_code,optional"` //安全密码
}

type FormRequest struct {
	Account  string `form:"account"`           //账号
	Password string `form:"password"`          //密码
	SecCode  string `form:"sec_code,optional"` //安全密码
}

type GetCaptchaRequest struct {
	Key string `path:"key"` //验证码key
}

type EditUserHeadImg struct {
	UserId  string   `json:"userId"`  //用户id
	HeadImg []string `json:"headImg"` //头像图片组
}

type UploadRequest struct {
	MyFile string `form:"myFile,file"` //文件
}

type UserListResponse struct {
	UserList []User `json:"userList"` //用户列表
}

type TokenResponse struct {
	Token string `json:"token"` //token
}

type User struct {
	Name     string `json:"name"`     //姓名
	Account  string `json:"account"`  //账号
	Password string `json:"password"` //密码
	UserVip
	HeadImg []string `json:"headImg"` //头像图片组
}

type TestNest struct {
	Test string `json:"test"` //测试
}

type UserVip struct {
	VipId    string `json:"vipId"`    //vipid
	VipLevel string `json:"vipLevel"` //vip等级
}

type DownloadRequest struct {
	FileDir  string `form:"fileDir,optional"` //文件夹
	FileName string `form:"fileName"`         //文件名
}

type Result struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
